#!/usr/bin/env python3
"""Generate compact 349-V1 compiled character frames from checked-in previews."""
from __future__ import annotations

import hashlib
import argparse
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import export_sd_pack as exporter  # noqa: E402

DEFAULT_OUTPUT = ROOT / "src/storage/v1_fallback_frames.h"
DEFAULT_SOURCE = ROOT / "assets/sd_preview"
MOOD_TIMES = {"sleep": 700, "thinking": 220}


def rooted(path: Path) -> Path:
    return (ROOT / path).resolve() if not path.is_absolute() else path.resolve()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                        help="preview root (default: assets/sd_preview in this checkout)")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                        help="generated header (default: src/storage/v1_fallback_frames.h)")
    args = parser.parse_args()
    source_root = rooted(args.source)
    output = rooted(args.output)
    storage_root = (ROOT / "src/storage").resolve()
    if not source_root.is_dir():
        raise SystemExit(f"preview source directory does not exist: {source_root}")
    if not output.is_relative_to(storage_root) or output.suffix not in {".h", ".hpp"}:
        raise SystemExit("output must be a .h/.hpp file under src/storage")
    if output == source_root or output.is_relative_to(source_root):
        raise SystemExit("output cannot overwrite a preview source")
    if output.exists() and output != DEFAULT_OUTPUT.resolve():
        raise SystemExit("refusing to overwrite an existing file other than the generated fallback header")

    source_hash = hashlib.sha256()
    frames: list[tuple[str, int, bytes]] = []
    for mood, names in exporter.STATE_MAP.items():
        for index, name in enumerate(names):
            path = source_root / mood / f"{index:03d}.png"
            if not path.is_file():
                raise SystemExit(f"missing checked-in preview: {path}")
            raw_source = path.read_bytes()
            source_hash.update(f"{mood}/{index:03d}.png\0".encode())
            source_hash.update(raw_source)
            with Image.open(path) as source:
                full = exporter.fit_v1_character(source)
            quantized = exporter.terminal_quantize(
                full, sleep_dim=(mood == "sleep"),
                size=(exporter.V1_W, exporter.V1_H), bottom_band=0,
            )
            # The SD image is full panel size; keep only the exporter-defined
            # 144x144 character region in firmware to save flash substantially.
            art = quantized.crop((0, exporter.V1_CHARACTER_Y,
                                  exporter.V1_CHARACTER_SIZE[0],
                                  exporter.V1_CHARACTER_Y + exporter.V1_CHARACTER_SIZE[1]))
            packed = exporter.pack4(art)
            exporter.validate_raw4(packed, *art.size, len(exporter.PAL))
            frames.append((mood, index, packed))

    exporter_hash = hashlib.sha256((ROOT / "scripts/export_sd_pack.py").read_bytes()).hexdigest()
    source_digest = source_hash.hexdigest()
    lines = [
        "// Generated by scripts/generate_v1_fallback.py; do not edit.",
        f"// Sources: assets/sd_preview (content digest {source_digest}).",
        f"// Quantization/crop implementation: scripts/export_sd_pack.py SHA-256 {exporter_hash}.",
        "#pragma once", "", "#include <stddef.h>", "#include <stdint.h>", "",
        "namespace storage { namespace fallback {",
        "constexpr uint16_t kWidth = 144;", "constexpr uint16_t kHeight = 144;",
        "constexpr size_t kFrameBytes = 144U * 144U / 2U;", "",
    ]
    for mood, index, packed in frames:
        lines.append(f"static const uint8_t k_{mood}_{index:03d}[kFrameBytes] = {{")
        for offset in range(0, len(packed), 16):
            lines.append("  " + ", ".join(f"0x{value:02X}" for value in packed[offset:offset + 16]) + ",")
        lines.append("};")
    lines.extend(["", "struct Frame { const char* mood; const uint8_t* data; uint16_t frameMs; };",
                  f"static const Frame kFrames[{len(frames)}] = {{"])
    # Keep the generated lookup table compact and its indices explicit.
    counters: dict[str, int] = {}
    for mood, _, _packed in frames:
        index = counters.get(mood, 0)
        counters[mood] = index + 1
        lines.append(f'  {{"{mood}", k_{mood}_{index:03d}, {MOOD_TIMES.get(mood, 180)}}},')
    lines.extend(["};", f"constexpr size_t kFrameCount = {len(frames)};", "} }  // namespace storage::fallback", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    try:
        display_path = output.relative_to(ROOT)
    except ValueError:
        display_path = output
    print(f"wrote {display_path} ({sum(len(f[2]) for f in frames)} packed bytes)")


if __name__ == "__main__":
    main()
