#!/usr/bin/env python3
"""Generate the tiny 12 px PUA coverage atlas from the pinned Meslo Nerd Font."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from PIL import ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "assets/nerd_icons/source/MesloLGSDZNerdFontMono-Regular.ttf"
OUTPUT = ROOT / "src/ui/nerd_icons_data.h"
FONT_SHA256 = "23f523b6c649dfa6df45f92da7e4b34c009756e4acb7106c0f5f771b9cc65b3b"
PILLOW_VERSION = "12.3.0"
FONTTOOLS_VERSION = "4.61.1"
FONT_SIZE = 12
LINE_HEIGHT = 12
BASELINE = 9
MAX_ADVANCE = 13
PUA_RANGES = ((0xE000, 0xF8FF), (0xF0000, 0xFFFFD))


def in_pua(codepoint: int) -> bool:
    return any(first <= codepoint <= last for first, last in PUA_RANGES)


def pua_codepoints(font_path: Path) -> list[int]:
    from fontTools.ttLib import TTFont

    font = TTFont(font_path, recalcBBoxes=False, recalcTimestamp=False)
    return sorted(codepoint for codepoint in font.getBestCmap() if in_pua(codepoint))


def pack_alpha4(image: Image.Image) -> bytes:
    """Pack row-major grayscale alpha; the even pixel occupies the low nibble."""
    from PIL import Image

    gray = image.convert("L")
    width, height = gray.size
    pixels = gray.tobytes()
    packed = bytearray()
    for y in range(height):
        row = pixels[y * width : (y + 1) * width]
        for x in range(0, width, 2):
            even = (row[x] + 8) // 17
            odd = (row[x + 1] + 8) // 17 if x + 1 < width else 0
            packed.append((odd << 4) | even)
    return bytes(packed)


def rasterize(font: ImageFont.FreeTypeFont, codepoint: int) -> tuple[bytes, int, int, int, int, int]:
    """Return packed mask, dimensions, advance, and line-top x/y offsets."""
    from PIL import Image

    mask, offset = font.getmask2(chr(codepoint), mode="L", anchor="ls")
    image = Image.frombytes("L", mask.size, bytes(mask))
    bounds = image.getbbox()
    if bounds is None:
        # U+EC03 is the upstream font's intentional zero-ink spacing glyph.
        return b"", 0, 0, max(1, round(font.getlength(chr(codepoint)))), 0, 0

    image = image.crop(bounds)
    left = bounds[0]
    x_offset = offset[0] + left
    # Normalize the rare oversized arrow/line glyphs to the existing 12 px line.
    scale = min(1.0, 13 / image.width, LINE_HEIGHT / image.height)
    if scale < 1:
        size = (max(1, round(image.width * scale)), max(1, round(image.height * scale)))
        image = image.resize(size, Image.Resampling.LANCZOS)

    width, height = image.size
    advance = min(MAX_ADVANCE, max(width + 1, round(font.getlength(chr(codepoint)))))
    # Keep each mask inside its measured token advance. Some Powerline glyphs
    # have negative source bearings or exceed the source's narrow advance.
    x_offset = min(max(x_offset, 0), advance - width)
    # Keep each mask inside one 12 px line and center it vertically.
    y_offset = (LINE_HEIGHT - height) // 2
    return pack_alpha4(image), width, height, advance, x_offset, y_offset


def generate(font_path: Path, output: Path) -> dict[str, int]:
    import fontTools
    from PIL import ImageFont, features

    if fontTools.__version__ != FONTTOOLS_VERSION:
        raise RuntimeError(f"fontTools {FONTTOOLS_VERSION} required")
    import PIL

    if PIL.__version__ != PILLOW_VERSION:
        raise RuntimeError(f"Pillow {PILLOW_VERSION} required")
    if features.version("freetype2") != "2.14.3":
        raise RuntimeError("Pillow FreeType 2.14.3 required for deterministic raster output")
    digest = hashlib.sha256(font_path.read_bytes()).hexdigest()
    if digest != FONT_SHA256:
        raise RuntimeError(f"font SHA256 mismatch: {digest}")

    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    cmap = pua_codepoints(font_path)
    records: list[tuple[int, int, int, int, int, int, int]] = []
    pixels = bytearray()
    largest_width = largest_height = largest_advance = 0
    empty = []
    for codepoint in cmap:
        alpha, width, height, advance, x_offset, y_offset = rasterize(font, codepoint)
        if not alpha:
            empty.append(codepoint)
        records.append((codepoint, len(pixels), width, height, advance, x_offset, y_offset))
        pixels.extend(alpha)
        largest_width = max(largest_width, width)
        largest_height = max(largest_height, height)
        largest_advance = max(largest_advance, advance)

    if empty != [0xEC03]:
        raise RuntimeError(f"unexpected empty PUA glyphs: {empty[:8]}")
    if largest_width > 13 or largest_height > LINE_HEIGHT or largest_advance > MAX_ADVANCE:
        raise AssertionError("atlas exceeded the configured glyph bounds")

    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("// Generated by scripts/generate_nerd_icons.py; do not edit.\n")
        stream.write("#pragma once\n#include <stdint.h>\n\nnamespace ui {\nnamespace nerd_icons_data {\n")
        stream.write("struct Entry { uint32_t codepoint; uint32_t offset; uint8_t width, height, advance; int8_t xOffset, yOffset; };\n")
        stream.write("constexpr uint8_t kLineHeight = 12;\n")
        stream.write(f"constexpr uint8_t kBaseline = {BASELINE};\n")
        stream.write(f"constexpr uint32_t kGlyphCount = {len(records)};\n")
        stream.write(f"constexpr uint32_t kPixelBytes = {len(pixels)};\n")
        stream.write("constexpr Entry kGlyphs[] = {\n")
        for codepoint, offset, width, height, advance, x_offset, y_offset in records:
            stream.write(
                f"  {{0x{codepoint:X}u, {offset}u, {width}, {height}, {advance}, {x_offset}, {y_offset}}},\n"
            )
        stream.write("};\nconstexpr uint8_t kAlpha4[] = {\n")
        for start in range(0, len(pixels), 16):
            row = pixels[start : start + 16]
            stream.write("  " + ", ".join(f"0x{value:02X}" for value in row) + ",\n")
        stream.write("};\n}  // namespace nerd_icons_data\n}  // namespace ui\n")

    return {
        "glyphs": len(records),
        "pixel_bytes": len(pixels),
        "largest_width": largest_width,
        "largest_height": largest_height,
        "largest_advance": largest_advance,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, default=FONT)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    try:
        result = generate(args.font, args.output)
    except (OSError, RuntimeError, AssertionError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(
        f"generated {result['glyphs']} glyphs, {result['pixel_bytes']} alpha4 bytes; "
        f"max {result['largest_width']}x{result['largest_height']}, "
        f"advance {result['largest_advance']} px"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
